export const data = [
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "Queue",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 2,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "yes",
    userIter: "",
    postBuild: "Post preview",
    postStatus: "On review",
  },
  {
    id: 3,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "Message sent",
    postBuild: "",
    postStatus: "Rejected",
  },
  {
    id: 4,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "Queue",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 5,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "",
  },
  {
    id: 6,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "Message sent",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 7,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "Queue",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 8,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "",
    postStatus: "",
  },
  {
    id: 9,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "",
    postBuild: "Post preview",
    postStatus: "Rejected",
  },
  {
    id: 10,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 11,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 12,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 13,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 14,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "Queue",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 15,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 16,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 17,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
];
