export const data = [
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
  {
    id: 1,
    scraping: "1.07.2023",
    linkPost: "Url",
    linkGroup: "URL",
    linkProfile: "http",
    message: "Text",
    aiStatus: "no",
    userIter: "send",
    postBuild: "Post preview",
    postStatus: "Posted",
  },
];
